version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: clipcut-redis
    ports:
      - "6379:6379"

  flask:
    build: .
    container_name: clipcut-flask
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis

  celery:
    build: .
    container_name: clipcut-celery
    command: celery -A app.celery worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    depends_on:
      - redis
